export const SET_EXTERNAL_VARIABLE = "SET_EXTERNAL_VARIABLE";
export const SET_ROW_COUNT = "SET_ROW_COUNT";
export const DELETE_VARIABLE = "DELETE_VARIABLE";
export const ADD_DERIVED = "ADD_DERIVED";
export const SET_DERIVED = "SET_DERIVED";
export const SET_WEBSOCKET_VARIABLE = "SET_WEBSOCKET_VARIABLE";
